apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'git@github.com:yourusername/your-repo.git'  # Use the SSH URL
    path: 'deploy'
    targetRevision: 'main'
    sshPrivateKeySecret:
      name: ssh-key-secret
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: 'node-app'
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
